---
title: The All-Seeing Pi
hero_image: images/banner.png
description: In this resource, you will make a tweeting touchscreen photo booth using a Raspberry Pi.
original_url: https://raspberrypi.org/learning/the-all-seeing-pi
theme: red
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 4, design-4, programming-4, phys-comp-4, manufacture-4, community-1
interests: photography, big-project
technologies: raspberry-pi, electronic-components, python
site_areas: projects
hardware: raspberry-pi, electronic-components
software: python
version: 3.0.2
last_tested: 2018-06-14
steps:
- title: Introduction
- title: What you will need
- title: Making the photo booth housing
- title: Connecting the Raspberry Pi touchscreen
- title: Connecting the Camera Module
- title: Connecting the buttons
- title: Finishing the setup
- title: Test the buttons
- title: Set up the camera
- title: Take a picture when the button is pressed
- title: Working with overlays
- title: Change overlays with a button
- title: Save an overlay on your picture
- title: Create a GUI
- title: Stop the picture overwriting
- title: Display the picture
- title: Tweet picture
- title: The All Seeing Pi (Overlay Functions)
- title: What next?
